services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    environment:
      PUID: 1000
      PGID: 1000
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
    restart: unless-stopped
    ports:
      - "8081:8081"